# Generated by Django 4.1.1 on 2022-10-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='title',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_agent_one',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_agent_two',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_one',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='user_two',
            field=models.CharField(default='nil', max_length=100),
        ),
    ]
