# Generated by Django 4.1.1 on 2022-10-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatboxdata_delete_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatboxdata',
            name='my_image',
            field=models.CharField(default='avatar.png', max_length=250),
        ),
        migrations.AddField(
            model_name='chatboxdata',
            name='other_image',
            field=models.CharField(default='avatar.png', max_length=250),
        ),
    ]
