# Generated by Django 4.1.1 on 2022-10-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.CharField(default='', max_length=250),
        ),
    ]
